### ISSUE TITLE
setting u and v for the camera poses

### ISSUE THREAD

**Issue by YoungJoongUNC** [autonomousvision/graf#9]
Hello! I would like to appreciate sharing your great work, it is indeed a wonderful work!

1)May I ask following question regarding the code of GRAF? I know that we control the camera poses by setting the min and max value of u and v. But I would like to know how exactly the camera poses (rotation, elevation) are calculated using u and v from the following codes.

u = azimuth / 360
v = 0.5* (1-cos(polar * pi/180))

I would greatly appreciate if you could explain this to me!

2)Also, if I have the dataset that has the image of a human face from every degree (0-360) then should I reset the u and v accordingly for the training? In that case, may I ask how could I set the u and v?

Thank you so much!

**Comment by katjaschwarz** [comment]
Hi, 

thanks :), of course! 

1) We sample the angles this way because sampling azimuth and polar angle directly from a uniform distribution would lead to a pose distribution that is not uniformly distributed on the sphere in the given range. You can find a detailed explanation e.g. [here](https://mathworld.wolfram.com/SpherePointPicking.html) or [here](https://www.bogotobogo.com/Algorithms/uniform_distribution_sphere.php).

2) Yes, in this case you set the values as follows: u=(0, 1), v=(0, 1), then u and v will both be sampled from the full range.
